version: '3.11.1'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    environment:
      - SECRET_KEY=django-insecure-c6l)2&gd8iacgz-z3srndc21bh3jv6lr(!h-n&2*pbs#(d18$w
      - DEBUG=1
      - STRIPE_TEST_PUBLISHABLE_KEY = pk_test_51MSoOrSJNTkbWxnLoKL067Pd6OQIBBaXFOpoM5AW6RsIu4FT984g8Qvg8peeZdNTdqSa7HWfrgDThNobq0loDHGu00DEhcj8LG
      - STRIPE_TEST_SECRET_KEY = sk_test_51MSoOrSJNTkbWxnLX7qPVwvnoMeSd1r2JeF6ehc828Bm6uBzy9KGRuSywn1guMpOabtwu12XCdVBwfOPTUc5C814007dp9yi5T
    volumes:
     - .:/code
    ports:
     - 8000:8000
    depends_on:
     - db
  db:
    image: postgres:11
    volumes:
     - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
volumes:
  postgres_data:
