version: '3.11.1'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    environment:
      - SECRET_KEY=django-insecure-c6l)2&gd8iacgz-z3srndc21bh3jv6lr(!h-n&2*pbs#(d18$w
      - DEBUG=1
    volumes:
     - .:/code
    ports:
     - 8000:8000
    depends_on:
     - db
  db:
    image: postgres:11
    volumes:
     - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
